version: 2

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    # ---- Core correctness ----
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

    # ---- Code quality ----
    - bodyclose
    - contextcheck
    - cyclop
    - dupl
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - godot
    - goprintffuncname
    - grouper
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace

linters-settings:
  cyclop:
    max-complexity: 15

  dupl:
    threshold: 100

  errcheck:
    check-type-assertions: true
    check-blank: true

  forbidigo:
    forbid:
      - pattern: ^print.*$
      - pattern: 'fmt\.Print.*'

  funlen:
    lines: 100
    statements: 50

  gocognit:
    min-complexity: 15

  goconst:
    min-len: 2
    min-occurrences: 3

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

  godot:
    scope: declarations
    exclude:
      - "^func Test"
      - "^func Benchmark"

  lll:
    line-length: 120

  misspell:
    locale: US

  nakedret:
    max-func-lines: 30

  nestif:
    min-complexity: 4

  nlreturn:
    block-size: 3

  prealloc:
    simple: true
    range-loops: true

  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - cyclop
        - dupl
        - funlen
        - gocognit

    - linters: [lll]
      source: "^//go:generate "

output:
  format: colored-line-number
